/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef patchUtils
#define patchUtils
#ifdef __cplusplus
extern "C" {
#endif

int applypatch(int argc, char *argv[]);

#ifdef __cplusplus
}
#endif
#endif
